baseURL = "https://jtia.la"
title = "jtia.la"
languageCode = "en-us"
paginate = 5
googleAnalytics = "UA-107120242-1"

[params]
  avatar = "avatar.jpg"
  author = "Joonas Tiala"
  author_title = "Software Developer"
  description = "Joonas Tiala - Software Developer"

  [[params.social]]
    name = "GitHub"
    icon = "logo-github"
    url = "https://github.com/jtiala"
  [[params.social]]
    name = "Twitter"
    icon = "logo-twitter"
    url = "https://twitter.com/tjiala"
  [[params.social]]
    name = "LinkedIn"
    icon = "logo-linkedin"
    url = "https://linkedin.com/in/jtiala"
  [[params.social]]
    name = "Email"
    icon = "mail"
    url = "mailto:joonas.tiala@gmail.com"

[markup]
  [markup.highlight]
    style = "dracula"
