baseURL = "https://jtia.la"
title = "jtia.la"
languageCode = "en-us"
paginate = 5
googleAnalytics = "UA-107120242-1"
disqusShortname = "jtiala"

[params]
  avatar = "avatar.jpg"
  author = "Joonas Tiala"
  description = "Hello. My name is Joonas and this is my blog."

  [[params.social]]
    name = "GitHub"
    icon = "logo-github"
    url = "https://github.com/jtiala"
  [[params.social]]
    name = "twitter"
    icon = "logo-twitter"
    url = "https://twitter.com/tjiala"
  [[params.social]]
    name = "Instagram"
    icon = "logo-instagram"
    url = "https://instagram.com/tjiala"
  [[params.social]]
    name = "LinkedIn"
    icon = "logo-linkedin"
    url = "https://linkedin.com/in/jtiala"
  [[params.social]]
    name = "Email"
    icon = "mail"
    url = "mailto:joonas.tiala@gmail.com"
