baseURL = "https://jtia.la"
title = "jtia.la"
languageCode = "en-us"
paginate = 5

[params]
  description = "Joonas Tiala - Software Developer"
  images = ["featured.png"]

  [params.author]
    name = "Joonas Tiala"
    title = "Software Developer"
    avatar = "avatar.jpg"

  [params.social]
    twitter = "tjiala"

  [[params.socialLinks]]
    name = "GitHub"
    icon = "fa6-brands:github"
    url = "https://github.com/jtiala"
  [[params.socialLinks]]
    name = "Bluesky"
    icon = "fa6-brands:bluesky"
    url = "https://bsky.app/profile/jtia.la"
  [[params.socialLinks]]
    name = "X"
    icon = "fa6-brands:x-twitter"
    url = "https://twitter.com/tjiala"
  [[params.socialLinks]]
    name = "LinkedIn"
    icon = "fa6-brands:linkedin"
    url = "https://linkedin.com/in/jtiala"
  [[params.socialLinks]]
    name = "Email"
    icon = "fa6-solid:at"
    url = "mailto:joonas.tiala@gmail.com"

[markup]
  [markup.highlight]
    style = "dracula"

[services]
  [services.googleAnalytics]
    ID = "G-MPSXQ3Q7GG"
